language: java
after_success:
  - bash <(curl -s https://codecov.io/bash)
sudo: required
cache:
  directories:
    - $HOME/.m2
script:
  - ./.travis/run.sh
install:
  - sudo apt-get update
env:
  global:
    - MAVEN_OPTS="-Xmx256m"
    - JAVA_OPTS="-Xmx256m"
jdk:
  - oraclejdk8